name: radx-analyzer

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.11
  - jupyterlab
  - ipykernel
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - black
  - pylint
  - vulture
